
import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <link rel="stylesheet" href="./css/bootstrap.min.css"  />
        <link rel="stylesheet" href="./css/style.css"  />
        <link rel="stylesheet" href="./css/vendors.css"  />
        <link rel="stylesheet" href="./css/custom.css"  />  
        {children}
      </body>
    </html>
  )
}
